### ISSUE TITLE
provider not working with a 6 node cluster (3 masters, 3 data )

### ISSUE THREAD

**Issue by kumar-shantanu** [phillbaker/terraform-provider-elasticsearch#109]
I have used this provider with a cluster with a single master+node setup, however, it's not working with a 3 master node setup(same version of elastic, etc). I tried with the option "sniff = false" as well but it's crashing with the 3 master node setup. 

Also to add, my elastic search (master nodes) is running behind an Nginx ingress, meaning the endpoint is distributing the request to different nodes in a round-robin fashion.

The log says, 

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2020-11-13T20:40:52.681Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1d284e7]
2020-11-13T20:40:52.681Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 
2020-11-13T20:40:52.681Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: goroutine 116 [running]:
2020-11-13T20:40:52.681Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: github.com/phillbaker/terraform-provider-elasticsearch/es.resourceElasticsearchIndexCreate(0xc0003a65b0, 0x20c7480, 0xc000410ea0, 0x2, 0x2e029c0)
2020-11-13T20:40:52.681Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	github.com/phillbaker/terraform-provider-elasticsearch/es/resource_elasticsearch_index.go:168 +0x3f7
2020-11-13T20:40:52.681Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00061e090, 0xc0004c6910, 0xc00000d7c0, 0x20c7480, 0xc000410ea0, 0x1ed0601, 0xc0001a4448, 0xc000181830)
2020-11-13T20:40:52.681Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.12.0/helper/schema/resource.go:310 +0x365
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000628000, 0xc000641a10, 0xc0004c6910, 0xc00000d7c0, 0xc00062b288, 0xc00000e630, 0x1ed5a20)
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.12.0/helper/schema/provider.go:294 +0x99
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0006120b8, 0x23cb160, 0xc0001809f0, 0xc000389ea0, 0xc0006120b8, 0xc0001809f0, 0xc0000cdb78)
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.12.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x20369c0, 0xc0006120b8, 0x23cb160, 0xc0001809f0, 0xc00008d0e0, 0x0, 0x23cb160, 0xc0001809f0, 0xc000520780, 0x250)
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.12.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000782600, 0x23d8f80, 0xc000783200, 0xc00018a800, 0xc0002003f0, 0x2dc89a0, 0x0, 0x0, 0x0)
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: google.golang.org/grpc.(*Server).handleStream(0xc000782600, 0x23d8f80, 0xc000783200, 0xc00018a800, 0x0)
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00078e1d0, 0xc000782600, 0x23d8f80, 0xc000783200, 0xc00018a800)
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-13T20:40:52.682Z [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020/11/13 20:40:52 [DEBUG] elasticsearch_index.dev-index["XXX"]: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/13 20:40:52 [TRACE] EvalMaybeTainted: elasticsearch_index.dev-index["XXX"] encountered an error during creation, so it is now marked as tainted
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalWriteState
2020/11/13 20:40:52 [TRACE] EvalWriteState: removing state object for elasticsearch_index.dev-index["XXX"]
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/11/13 20:40:52 [TRACE] EvalApplyProvisioners: elasticsearch_index.dev-index["XXX"] has no state, so skipping provisioners
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/13 20:40:52 [TRACE] EvalMaybeTainted: elasticsearch_index.dev-index["XXX"] encountered an error during creation, so it is now marked as tainted
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalWriteState
2020/11/13 20:40:52 [TRACE] EvalWriteState: removing state object for elasticsearch_index.dev-index["XXX"]
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalIf
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalIf
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalWriteDiff
2020/11/13 20:40:52 [TRACE] eval: *terraform.EvalApplyPost
2020/11/13 20:40:52 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/11/13 20:40:52 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/11/13 20:40:52 [TRACE] [walkApply] Exiting eval tree: elasticsearch_index.dev-index["XXX"]
2020/11/13 20:40:52 [TRACE] vertex "elasticsearch_index.dev-index[\"XXX\"]": visit complete
2020/11/13 20:40:52 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/phillbaker/elasticsearch\"] (close)" errored, so skipping
2020/11/13 20:40:52 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/11/13 20:40:52 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-11-13T20:40:52.685Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/phillbaker/elasticsearch/1.5.0/darwin_amd64/terraform-provider-elasticsearch_v1.5.0 pid=33219 error="exit status 2"
2020-11-13T20:40:52.685Z [DEBUG] plugin: plugin exited

FAILURE: Build failed with an exception.

**Comment by kumar-shantanu** [comment]
Closing this.
