### ISSUE TITLE
Role resource import crashing

### ISSUE THREAD

**Issue by yogsoft** [phillbaker/terraform-provider-elasticsearch#150]
Below command is crashing in v1.5.3 and v1.5.2, however it works in v1.5.1. 

Older version (v1.5.1) cannot be used because it lack document level security in role source and tenant resource is missing.

terraform import elasticsearch_opendistro_role.writer logs_writer

Environment: 
Opendistro 7.8
Terraform 14

Role JSON:
```json
{
  "index_permissions": [
    {
      "index_patterns": [
        "*"
      ],
      "dls": "",
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "crud",
        "create_index"
      ]
    }
  ],
  "tenant_permissions": [],
  "cluster_permissions": [
    "cluster_composite_ops"
  ]
}
```

Logs:
```
terraform import elasticsearch_opendistro_role.writer log_writer
elasticsearch_opendistro_role.writer: Importing from ID "log_writer"...
elasticsearch_opendistro_role.writer: Import prepared!
  Prepared elasticsearch_opendistro_role for import
elasticsearch_opendistro_role.writer: Refreshing state... [id=log_writer]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [0] with length 0
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: 
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: goroutine 37 [running]:
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: github.com/phillbaker/terraform-provider-elasticsearch/es.flattenIndexPermissions(0xc0001b01c0, 0x1, 0x4, 0xc00034ecb0, 0xc0007426e0, 0x0, 0x0)
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    github.com/phillbaker/terraform-provider-elasticsearch/es/util.go:348 +0x726
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: github.com/phillbaker/terraform-provider-elasticsearch/es.resourceElasticsearchOpenDistroRoleRead(0xc00034ecb0, 0x121d420, 0xc00012e000, 0xc00034ecb0, 0x0)
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    github.com/phillbaker/terraform-provider-elasticsearch/es/resource_elasticsearch_opendistro_role.go:155 +0x6ae
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000384a20, 0xc0005e6f50, 0x121d420, 0xc00012e000, 0xc00000ec88, 0x0, 0x0)
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    github.com/hashicorp/terraform-plugin-sdk@v1.12.0/helper/schema/resource.go:460 +0x119
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000716048, 0x182d380, 0xc0001626c0, 0xc0007268a0, 0xc000716048, 0xc0001626c0, 0xc0005fcb78)
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    github.com/hashicorp/terraform-plugin-sdk@v1.12.0/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1474460, 0xc000716048, 0x182d380, 0xc0001626c0, 0xc000726840, 0x0, 0x182d380, 0xc0001626c0, 0xc0003da140, 0x9e)
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    github.com/hashicorp/terraform-plugin-sdk@v1.12.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000782600, 0x183b320, 0xc000783380, 0xc0000ba400, 0xc000382930, 0x2249170, 0x0, 0x0, 0x0)
2021-03-06T09:38:54.009-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2021-03-06T09:38:54.010-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: google.golang.org/grpc.(*Server).handleStream(0xc000782600, 0x183b320, 0xc000783380, 0xc0000ba400, 0x0)
2021-03-06T09:38:54.010-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2021-03-06T09:38:54.010-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000388180, 0xc000782600, 0x183b320, 0xc000783380, 0xc0000ba400)
2021-03-06T09:38:54.010-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2021-03-06T09:38:54.010-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-03-06T09:38:54.010-0600 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.3:    google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2021/03/06 09:38:54 [TRACE] vertex "import elasticsearch_opendistro_role.writer result": visit complete
2021/03/06 09:38:54 [TRACE] vertex "elasticsearch_opendistro_role.writer (import id \"log_writer\")": dynamic subgraph encountered errors
2021/03/06 09:38:54 [TRACE] vertex "elasticsearch_opendistro_role.writer (import id \"log_writer\")": visit complete
2021/03/06 09:38:54 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/phillbaker/elasticsearch\"] (close)" errored, so skipping
2021/03/06 09:38:54 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-03-06T09:38:54.011-0600 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/phillbaker/elasticsearch/1.5.3/linux_amd64/terraform-provider-elasticsearch_v1.5.3 pid=4122 error="exit status 2"
2021-03-06T09:38:54.011-0600 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by phillbaker** [comment]
Hi @yogsoft can you include the logs of the crash and the JSON representation for the opendistro role?

**Comment by yogsoft** [comment]
@phillbaker added role json and crash logs.

**Comment by yogsoft** [comment]
@phillbaker thank you for the fix. Any idea this will be released to terraform registry?

**Comment by phillbaker** [comment]
Just tagged 1.5.4
