### ISSUE TITLE
Refresh / Update of Open Distro Role fails if an index permission is added manually via Kibana

### ISSUE THREAD

**Issue by zjanc** [phillbaker/terraform-provider-elasticsearch#235]
Hi,

Encountering issues with OpenDistro role resources if the index permissions for a role has been modified manually (e.g. added an index permission outside Terraform). Specifically, it breaks if current number of index permissions under the role > number of index permissions in the state file.

## Steps to reproduce:
- Create and apply an `elasticsearch_opendistro_role`
- Manually add an index permission under the created role using Kibana
- Run `refresh`/`plan`/`apply`

## Additional investigation
Since the error is `index out of range` I tested the following scenarios:
- Adding an empty dict to the `index_permissions` array in the state file of the `elasticsearch_opendistro_role` resource so the number of index_permission entries match those in the cluster
  - Returned the same `panic: runtime error: index out of range [7] with length 7` error
- Duplicating an existing dict in the `index_permissions` array in the state file of the `elasticsearch_opendistro_role` resource so the number of index_permission entries match those in the cluster
  - Returned the same `panic: runtime error: index out of range [7] with length 7` error
- Adding a new dict with the `index_patterns` field matching the manually added one (all other fields out of sync) + matching the number of index_permission entries in the cluster
  - This worked. After running `refresh` with this state file, the resource state was updated.

## Current mitigation:
- As a workaround, we untrack/manually delete the `elasticsearch_opendistro_role` resource from the state file and then reimport it, fixing the issue

## Excerpt from trace:
```
panic: runtime error: index out of range [7] with length 7
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1:
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1: goroutine 131 [running]:
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1: github.com/phillbaker/terraform-provider-elasticsearch/es.flattenIndexPermissions(0xc0003ad800, 0x8, 0x9, 0xc000538850, 0xc0008361e0, 0x0, 0x0)
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1:    github.com/phillbaker/terraform-provider-elasticsearch/es/util.go:428 +0x750
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1: github.com/phillbaker/terraform-provider-elasticsearch/es.resourceElasticsearchOpenDistroRoleRead(0xc000538850, 0x1df1700, 0xc00053b900, 0xc000538850, 0x0)
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1:    github.com/phillbaker/terraform-provider-elasticsearch/es/resource_elasticsearch_opendistro_role.go:157 +0x76a
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000b4ea0, 0xc000210690, 0x1df1700, 0xc00053b900, 0xc00000eaa0, 0x0, 0x0)
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1:    github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/resource.go:460 +0x12e
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0006a48b0, 0x22967f0, 0xc00070c270, 0xc00090a2a0, 0xc0006a48b0, 0xc00070c270, 0xc0000c8ba0)
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1:    github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1ff6540, 0xc0006a48b0, 0x22967f0, 0xc00070c270, 0xc00090a240, 0x0, 0x22967f0, 0xc00070c270, 0xc000b0e700, 0x6a9)
2021-12-23T12:30:46.926+0800 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.1:    github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214

```

**Additional Information:**
- Terraform version: `0.14.11`
- Provider version: `1.6.1`
- ES version: `7.10.2`

**Comment by phillbaker** [comment]
Thanks for the detailed bug report, will take a look!

**Comment by phillbaker** [comment]
Hello, the code that was throwing this error has been removed in the latest beta releases due to removing the deprecated `fls` attribute: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/c28d2dec3f5c366de4d694149a1d6489471ea79b/es/util.go#L426-L431

I'm going to close this issue for now as already resolved, please upgrade the version of the provider you're using.
